
server:
  port: 8080
spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/exam?useSSL=false
        username: root
        password: p@swrd123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
      view:
        prefix: /WEB-INF/page/
        suffix: .jsp
    mail:
      host: smtp.sina.cn
      username: weikaisen_job@sina.com
      password: mixiu612
      default-encoding: utf-8
mybatis:
  mapper-locations: classpath:mybatis/mapping/*.xml
  type-aliases-package: com.jiyinhui.exam.entity.*
  config-location: classpath:mybatis/mybatis-config.xml
  type-handlers-package: com.jiyinhui.exam.config.mybatis.handler.*

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

mail:
    fromMail:
        addr: weikaisen_job@sina.com
